Clean up: live paper version
openMetadataInitiative/openMINDS_publications pull request #13
Opened 2023-02-16 10:33 UTC by UlrikeS91

MINOR changes:
- improved instructions 
- establish alphabetical order
- renamed `lastModified` to `modificationDate` to adhere to new convention, reduce list of property names and because it fits the needs in this schema (instructions state that the date of the last modification should be entered)

MAJOR changes:
- removed `relatedPublication` and adjusted them in the concept schema to fit the needs for this schema; please see https://github.com/HumanBrainProject/openMINDS_core/pull/387:
     - added `ISSN` there
     - adjusted instructions to fit the original ones from here better 
     - NOTE: By doing this change, `livePaperSection` will gain `HANDLE` as allowed value, is this ok @apdavison? 

SPECIAL ATTENTION:
none

2023-02-20 10:56 UTC, lzehl requested changes

2023-02-20 10:56 UTC, lzehl commented on schemas/livePaperVersion.schema.tpl.json
> +      "_instruction": "Add all datasets, models and/or software that are part of or described by this live paper version.",
"... that are part of or are described by..."

2023-02-27 12:03 UTC, apdavison approved these changes

2023-02-27 12:03 UTC, apdavison commented on schemas/livePaperVersion.schema.tpl.json
> +        "_instruction": "Enter the date and time on which this live paper version was last modfied, formatted as '2023-02-07T16:00:00+00:00'."
typo: "modfied" --> "modified"

2023-03-02 14:39 UTC, lzehl approved these changes
@apdavison please double check the updates I've made to this PR and merge if you approve

2023-03-02 14:39 UTC, lzehl approved these changes

2023-03-06 13:23 UTC, Peyman-N approved these changes

2023-03-06 13:23 UTC, merged